# This is a basic workflow to help you get started with Actions

name: send payload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
    types:  [closed]
    
env:
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
  WEBHOOK_CONTENT_TYPE: application/json
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  payload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Send payload to endpoint
        uses: distributhor/workflow-webhook@v2.0.3
        with:
          url: https://endpointtest20230412121510.azurewebsites.net/api/Github/Receive
          method: POST
          headers: |
            Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}
            Content-Type: application/json
          json: |
            {
              "commit": "${{ github.event.pull_request.merge_commit_sha }}",
             
            }
