# This is a basic workflow to help you get started with Actions

name: send payload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
    types:  [closed]
    

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  payload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Construct push event payload
        id: push_payload
        run: |
          push_payload=$(echo "${{ github.event.pull_request.head }}" | jq -s '.[0] | {
          ref: "refs/heads/main",
          before: $ARGS.positional[0].base.sha,
          after: $ARGS.positional[0].sha,
          created: false,
          deleted: false,
          forced: false,
          base_ref: null,
          compare: "https://github.com/${{ github.repository }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}",
          commits: $ARGS.positional[0].commits
           }')
 

      
      - name: Send payload to endpoint
        uses: distributhor/workflow-webhook@v2.0.3
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_payload: ${{ steps.push_payload.outputs.push_payload }}
          
       
