name: Send Push Payload
on:
  push:
    paths:
      - 'Dataextraction/api/*'

jobs:
  send_payload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Send push payload
      uses: distributhor/webhook-action@v2.0.3
      with:
        url: 'https://endpointtest20230320150036.azurewebsites.net/api/Github/Receive'
        method: POST
        payload: ${{ toJson(github.event) }}
        content-type: application/json
        secret: ${{ secrets.WEBHOOK_SECRET }}
