name: Send Push Payload
on:
  push:
    paths:
      - 'Dataextraction/api/*'

jobs:
  send_payload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Send push payload
      uses: distributhor/workflow-webhook@v2.0.3
      with:
        url: 'https://endpointtest20230320150036.azurewebsites.net/api/Github/Receive'
        method: 'POST'
        data: ${{ toJson(github.event) }}
        headers: |
            Content-Type: application/json
            Authorization: Bearer ${{ secrets.WEBHOOK_SECRET  }}
