name: hook to APIDocumentation Middleware
on:
  push:
    branches: [ main ]
    paths:
      - '.*/api/**/*'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the push is for API documentation file
        uses: distributhor/webhook-action@v2.0.3
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: POST
          payload: |
            {
              "data": "${{ github.event_path }}"
            }
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
       






      
    
        
      
        
        
