name: hook to APIDocumentation Middleware
on:
  push:
    paths:
      - '*/api/**/*'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the push is for API documentation file
        uses: distributhor/webhook-action@v2.0.3
        env:
            webhook_type: 'json-extended'
            webhook_url: ${{ secrets.WEBHOOK_URL }}
            webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
       






      
    
        
      
        
        
