name: Send Push Payload
on:
  push: 
    branches:
      - main
      - master
    paths:
      - '*/Dataextraction/api/*'

jobs:
  send_payload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Send push payload
      uses: distributhor/workflow-webhook@v2.0.3
      env:
        webhook_type: 'json-extended'
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
